spring:
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/db_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    servlet:
      path: /
    static-path-pattern: /static/**
    date-format: yyyy-MM-dd hh:mm:ss
#    spring.datasource.schema是用于执行ddl，可用于建表等功能
#    schema:
#      - classpath:sql/xxx.sql
mybatis:
  mapper-locations: classpath:mapper/*.xml